version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-node

    environment:
      JVM_OPTS: -Xmx3200m

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-v1-{{ checksum "package.json" }}-{{ checksum "RNCMIFTest/package.json" }}-{{ checksum "android/build.gradle" }}-{{ checksum "RNCMIFTest/android/build.gradle" }}-{{ checksum "RNCMIFTest/android/app/build.gradle" }}
          - deps-v1-

      - run: cd RNCMIFTest && yarn
      - run: cd RNCMIFTest/android && ./gradlew androidDependencies

      - save_cache:
          paths:
            - node_modules
            - RNCMIFTest/node_modules
            - RNCMIFTest/android/.gradle
          key: deps-v1-{{ checksum "package.json" }}-{{ checksum "RNCMIFTest/package.json" }}-{{ checksum "android/build.gradle" }}-{{ checksum "RNCMIFTest/android/build.gradle" }}-{{ checksum "RNCMIFTest/android/app/build.gradle" }}

      - run: cd RNCMIFTest && yarn build:android
      # - run: yarn reset:packager & yarn test:android